### ISSUE TITLE
Failed to resolve gradle

### ISSUE THREAD

**Issue by fadzley** [mthli/Knife#13]
Hi
I'm trying to use your library but the gradle failed to resolved compile 'com.github.mthli:Knife:v1.1'

**Comment by fadzley** [comment]
nevermind solved it.thanks

**Comment by songyingxin** [comment]
I have the same problem, please nevermind solve it ,thanks.

**Comment by niorx** [comment]
For future consumers: move maven { url 'https://jitpack.io' } from buildscript{ repositories{ to allprojects{ repositories{
Hope it helps.
